### ISSUE TITLE
Possible to backport to Kibana 4.x?

### ISSUE THREAD

**Issue by ThomasFlanaghan** [nreese/ez-query#1]
Hi,

Is it possible to back port this to kibana 4.x?

**Comment by nreese** [comment]
Clone the 4.x branch and give that a spin

**Comment by ThomasFlanaghan** [comment]
Working perfectly now thanks, Is there any way to query date ranges or is it just string queries for now? 
This makes usability much better for Kibana so thanks for the plugin either way!

**Comment by nreese** [comment]
I would recommend using https://github.com/nreese/kibana-time-plugin for time selection. If that does not meet your needs, provide a little more details about what you are looking for

**Comment by ThomasFlanaghan** [comment]
Hi,
We have that plugin and it works well for just switching dates but we want the same check box filtering you have currently so we can save date ranges e.g.
first checkbox : Transactions Quarter 1, Query would be: date between 1st april to 1st august.
second check box: Transactions Quarter 2, Query would be: date between 1st august 31st oct.
etc..

This way we can quickly show date for each quarter or select all boxes for the whole year. 

Thanks for your help,
Tom

**Comment by nreese** [comment]
That usecase makes a lot of sense. I create a [new issue](https://github.com/nreese/ez-query/issues/2) where the discussion can continue. I am going to close this issue now that kibana 4 is supported
